### PR TITLE
Use token auth for publishing rather than username and password

### PR DESCRIPTION
**Pull request by elo2112**

### CODE REVIEW

**Comment by elo2112** [comment]
Since we're not making use of a username anyway, I'd like to propose this as an alternative.

**Comment by barmintor** [comment]
I'd like to loop @cgalarza in on this, since you two are the first implementers of the publish webhook from Hyacinth. Is there anything we lose here? Nothing jumps out at me (password collision seems pretty low, and the user name is not a secret), but it would require a change to AC, so I want to talk it out. Longer term I would like to use a client cert, but that's a way off.

**Comment by elo2112** [comment]
FYI: Just rebased this branch off of recent commit master, removing subsites.yml from the repo.  Don't want that api key subsites.yml attribute in there, regardless of whether we're doing basic auth or token auth.

**Comment by elo2112** [comment]
Also copied subsites.yml to the shared/config directory on deployed servers so there are no surprises when we next deploy dcv to dev/test/staging/prod.

**Comment by cgalarza** [comment]
Moving to use tokens instead of credentials sounds good to me.

**Comment by barmintor** [comment]
Ok, I'm :+1: then. Thanks for coordinating, y'all! @cgalarza, I opened https://issues.cul.columbia.edu/browse/ACHYDRA-213 in parallel. Can you try to get that change up on dev/test?

**Comment by elo2112** [comment]
Thanks, everyone!

**Comment by cgalarza** [comment]
@barmintor I'll try to get a pull request by the end of the day. @elo2112 Thanks for providing a great example to work off of!

**Comment by elo2112** [comment]
@barmintor's code and tests were very easy to modify!  Great testing examples there. 👍

**Pull request merged**
